version: '3.8'

services:
  quickscene:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: quickscene-app
    volumes:
      # Mount data directories for persistence
      - ../data:/app/data
      - ../logs:/app/logs
      # Mount config for easy updates
      - ../config:/app/config:ro
    environment:
      - QUICKSCENE_CONFIG=/app/config/production.yaml
      - PYTHONPATH=/app
    # Resource limits for CPU-only operation
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 8G
        reservations:
          cpus: '2.0'
          memory: 4G
    # Restart policy
    restart: unless-stopped
    # Health check
    healthcheck:
      test: ["CMD", "python", "-c", "import app; print('OK')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add monitoring service
  # monitoring:
  #   image: prom/prometheus:latest
  #   container_name: quickscene-monitoring
  #   ports:
  #     - "9090:9090"
  #   volumes:
  #     - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

volumes:
  quickscene_data:
    driver: local
  quickscene_logs:
    driver: local
